# Generated by Django 2.0.13 on 2019-05-14 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='post',
            new_name='designation',
        ),
    ]
